---
# tasks file for deregister_rhel_subscription

- name: Unregister insights-client
  ansible.builtin.command: >
    insights-client --unregister
  become: yes
  ignore_errors: yes
  
- name: Deregister RHEL instance subscription
  redhat_subscription:
    state: absent
    activationkey: "{{ rh_activationkey }}"
    org_id: "{{ rh_org_id }}"
    release: "{{ rh_release }}"
  become: yes
  register: dereg_sub
  until: dereg_sub is not failed
  retries: 5
  ignore_errors: yes

- name: Update stage tag to deregistered
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ hostvars[inventory_hostname]['instance_id'] }}"
    state: present
    tags:
      Stage: "deregistered"
  delegate_to: localhost
  when: dereg_sub is not failed
